\set ON_ERROR_STOP on
-- Generated by scripts/tool_contracts.py from
-- db/config/agent_tool_contracts.json. Do not edit this file by hand.

UPDATE mosaic.agent_tool_contract
SET enabled = false
WHERE tool_name IN ('search_catalog', 'explain_recommendation');

INSERT INTO mosaic.agent_tool_contract (
    tool_name, tool_version, description, input_schema, output_schema, read_only
)
VALUES
    ('search_products', '1.0', 'Run filtered lexical, fuzzy, semantic, reciprocal-rank fusion, and bounded reranking over Aurora PostgreSQL.', '{"additionalProperties":false,"properties":{"attributes":{"type":["object","null"]},"availability":{"enum":["in_stock","low_stock","out_of_stock","preorder","discontinued",null],"type":["string","null"]},"brand":{"type":["string","null"]},"category_key":{"type":["string","null"]},"domain":{"enum":["consumer_electronics","running_fitness","home_office",null],"type":["string","null"]},"in_stock_only":{"type":"boolean"},"limit":{"maximum":2,"minimum":1,"type":"integer"},"max_price_cents":{"minimum":0,"type":["integer","null"]},"min_price_cents":{"minimum":0,"type":["integer","null"]},"min_rating":{"maximum":5,"minimum":0,"type":["number","null"]},"query":{"maxLength":1000,"minLength":1,"type":"string"}},"required":["query"],"type":"object"}'::jsonb, '{"properties":{"diagnostics":{"type":["object","null"]},"results":{"type":"array"},"search_event_id":{"format":"uuid","type":"string"}},"required":["search_event_id","results"],"type":"object"}'::jsonb, true),
    ('get_product_evidence', '1.0', 'Rank source-addressable specifications and reviews for one retrieved product against a focused evidence question.', '{"additionalProperties":false,"properties":{"evidence_query":{"minLength":1,"type":"string"},"product_id":{"minimum":1,"type":"integer"}},"required":["product_id","evidence_query"],"type":"object"}'::jsonb, '{"properties":{"evidence":{"type":"array"},"product_id":{"type":"integer"}},"required":["product_id","evidence"],"type":"object"}'::jsonb, true),
    ('compare_products', '1.0', 'Compare two to five products already retrieved during the current agent turn.', '{"additionalProperties":false,"properties":{"product_ids":{"items":{"minimum":1,"type":"integer"},"maxItems":5,"minItems":1,"type":"array","uniqueItems":true}},"required":["product_ids"],"type":"object"}'::jsonb, '{"properties":{"ok":{"type":"boolean"},"products":{"type":"array"}},"required":["ok","products"],"type":"object"}'::jsonb, true),
    ('explain_retrieval', '1.0', 'Replay persisted arm ranks, scores, fusion contributions, reranker order, and timings for one event created by the current agent turn.', '{"additionalProperties":false,"properties":{"search_event_id":{"format":"uuid","type":"string"}},"required":["search_event_id"],"type":"object"}'::jsonb, '{"properties":{"candidates":{"type":"array"},"ok":{"type":"boolean"},"search_event":{"type":["object","null"]}},"required":["ok","search_event","candidates"],"type":"object"}'::jsonb, true),
    ('synthesize_cited_answer', '1.0', 'Create the answer of record from retrieved products and evidence, with citation bounds and deterministic claim checks.', '{"additionalProperties":false,"properties":{"product_ids":{"items":{"minimum":1,"type":"integer"},"maxItems":6,"minItems":2,"type":"array","uniqueItems":true},"question":{"minLength":1,"type":"string"}},"required":["question","product_ids"],"type":"object"}'::jsonb, '{"properties":{"answer":{"type":"string"},"citations":{"type":"array"},"ok":{"type":"boolean"}},"required":["ok","answer","citations"],"type":"object"}'::jsonb, true)
ON CONFLICT (tool_name, tool_version) DO UPDATE
SET description = EXCLUDED.description,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema,
    read_only = EXCLUDED.read_only,
    enabled = true;
