"""Code generated by agent/generate_gateway_dispatch.py from agent/registry.py.

Do not edit by hand: run ``python -m agent.generate_gateway_dispatch`` to
regenerate. Gate G-17 fails CI if this file drifts from the registry.
"""
from __future__ import annotations

from typing import Any, Callable

from backend.app.agent import (
    answer_with_citations_impl,
    compare_sources_impl,
    decompose_question_impl,
    explain_ranking_impl,
    follow_evidence_links_impl,
    search_evidence_impl,
    synthesize_cited_answer_from_runs_impl,
)


def _opt_int(value: Any, default: int) -> int:
    return default if value is None else int(value)


def _opt_float(value: Any, default: float) -> float:
    return default if value is None else float(value)


def _opt_bool(value: Any) -> bool | None:
    return None if value is None else bool(value)


def _run_ids(args: dict[str, Any]) -> list[str]:
    """Read run_ids, coercing a legacy scalar run_id to a one-element list."""
    run_ids = args.get("run_ids")
    if run_ids:
        return [str(value) for value in run_ids]
    single = args.get("run_id")
    return [str(single)] if single else []


def _tool_decompose_question(args: dict[str, Any]) -> dict[str, Any]:
    return decompose_question_impl(question=str(args.get("question") or ""))


def _tool_search_evidence(args: dict[str, Any]) -> dict[str, Any]:
    return search_evidence_impl(
        query=str(args.get("query") or ""),
        incident_id=args.get("incident_id"),
        cluster_id=args.get("cluster_id"),
        kinds=args.get("kinds"),
        limit=_opt_int(args.get("limit"), 8),
        account_name=args.get("account_name"),
        severities=args.get("severities"),
        environment=args.get("environment"),
        service_name=args.get("service_name"),
        engine_version=args.get("engine_version"),
        aws_region=args.get("aws_region"),
        start_date=args.get("start_date"),
        end_date=args.get("end_date"),
        candidate_pool=_opt_int(args.get("candidate_pool"), 24),
        rrf_k=_opt_int(args.get("rrf_k"), 60),
        w_text=_opt_float(args.get("w_text"), 2.0),
        w_vector=_opt_float(args.get("w_vector"), 1.0),
        w_trgm=_opt_float(args.get("w_trgm"), 1.0),
        fuzzy_threshold=_opt_float(args.get("fuzzy_threshold"), 0.3),
        ef_search=_opt_int(args.get("ef_search"), 40),
        iterative_scan=str(args.get("iterative_scan")) if args.get("iterative_scan") is not None else "strict_order",
        rerank=_opt_bool(args.get("rerank")),
        principal=args.get("principal"),
    )


def _tool_follow_evidence_links(args: dict[str, Any]) -> dict[str, Any]:
    return follow_evidence_links_impl(
        seed_external_keys=args.get("seed_external_keys") or [],
        max_depth=_opt_int(args.get("max_depth"), 2),
        principal=args.get("principal"),
    )


def _tool_compare_sources(args: dict[str, Any]) -> dict[str, Any]:
    return compare_sources_impl(
        external_keys=args.get("external_keys") or [],
        principal=args.get("principal"),
    )


def _tool_explain_ranking(args: dict[str, Any]) -> dict[str, Any]:
    return explain_ranking_impl(run_id=str(args.get("run_id") or ""))


def _tool_synthesize_cited_answer(args: dict[str, Any]) -> dict[str, Any]:
    return synthesize_cited_answer_from_runs_impl(
        question=str(args.get("question") or ""),
        run_ids=_run_ids(args),
        limit=_opt_int(args.get("limit"), 8),
    )


def _tool_answer_with_citations(args: dict[str, Any]) -> dict[str, Any]:
    return answer_with_citations_impl(
        question=str(args.get("question") or ""),
        incident_id=args.get("incident_id"),
        cluster_id=args.get("cluster_id"),
        kinds=args.get("kinds"),
        limit=_opt_int(args.get("limit"), 8),
        account_name=args.get("account_name"),
        severities=args.get("severities"),
        environment=args.get("environment"),
        service_name=args.get("service_name"),
        engine_version=args.get("engine_version"),
        aws_region=args.get("aws_region"),
        start_date=args.get("start_date"),
        end_date=args.get("end_date"),
        candidate_pool=_opt_int(args.get("candidate_pool"), 24),
        rrf_k=_opt_int(args.get("rrf_k"), 60),
        w_text=_opt_float(args.get("w_text"), 2.0),
        w_vector=_opt_float(args.get("w_vector"), 1.0),
        w_trgm=_opt_float(args.get("w_trgm"), 1.0),
        fuzzy_threshold=_opt_float(args.get("fuzzy_threshold"), 0.3),
        ef_search=_opt_int(args.get("ef_search"), 40),
        iterative_scan=str(args.get("iterative_scan")) if args.get("iterative_scan") is not None else "strict_order",
        rerank=bool(args.get("rerank")) if args.get("rerank") is not None else False,
        max_tool_calls=_opt_int(args.get("max_tool_calls"), 12),
        max_escalations=_opt_int(args.get("max_escalations"), 2),
        principal=args.get("principal"),
    )


Tool = Callable[[dict[str, Any]], dict[str, Any]]
TOOLS: dict[str, Tool] = {
    "decompose_question": _tool_decompose_question,
    "search_evidence": _tool_search_evidence,
    "follow_evidence_links": _tool_follow_evidence_links,
    "compare_sources": _tool_compare_sources,
    "explain_ranking": _tool_explain_ranking,
    "synthesize_cited_answer": _tool_synthesize_cited_answer,
    "answer_with_citations": _tool_answer_with_citations,
}
