// Code generated by agent/generate_mcp_server.py from agent/registry.py.
// Do not edit by hand: run `python -m agent.generate_mcp_server` to regenerate.
// Gate G-17 fails CI if this file drifts from the registry.
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

type Post = (path: string, payload: Record<string, unknown>) => Promise<unknown>;
type Wrap = (result: unknown) => { content: { type: "text"; text: string }[] };

function pruneUndefined(payload: Record<string, unknown>): Record<string, unknown> {
  for (const key of Object.keys(payload)) {
    if (payload[key] === undefined) delete payload[key];
  }
  return payload;
}

export function registerTools(server: McpServer, post: Post, wrap: Wrap): void {
  server.tool(
    "decompose_question",
    `Break the diagnostic question into the three evidence findings Aurora can answer.

Call this first. It extracts the incident identifiers and returns the
backfill/write-stall, pool-exhaustion/recovery, and plan-regression
subquestions, so later searches stay scoped to measured evidence.

Returns:
    Detected identifiers, inferred filters, and ordered subquestions.`,
    {
      question: z.string().min(1).max(4000),
      role: z.enum(["app_engineer", "auditor", "dba"]).default("app_engineer"),
    },
    async (args: Record<string, unknown>) => {
      const payload = pruneUndefined({
        question: args.question,
        role: args.role,
      });
      return wrap(await post("/v1/tools/decompose", payload));
    }
  );

  server.tool(
    "search_evidence",
    `Retrieve evidence from Aurora using hybrid retrieval, and persist a receipt.

Runs all four signals in one SQL statement: exact identifier, full text,
pgvector semantic, and trigram fuzzy. Exact identifier matches are returned
as a tier above the fused candidates, so a named identifier cannot be
outranked. The Hybrid Retrieval Agent binds diagnostic searches to the
completed Wave A capture when the incident is known. Keep the returned
run_id: explain_ranking and synthesize_cited_answer both require it.

Returns:
    run_id, the ranked rows with their match tier, and the ranking groups.`,
    {
      query: z.string().min(1).max(2000),
      incident_id: z.string().optional(),
      cluster_id: z.string().optional(),
      kinds: z.array(z.enum(["incident", "change", "lock_evidence", "telemetry"])).optional(),
      limit: z.number().int().min(1).max(50).default(8),
      source_systems: z.array(z.string()).optional(),
      account_name: z.string().optional(),
      severities: z.array(z.string()).optional(),
      environment: z.string().optional(),
      service_name: z.string().optional(),
      engine_version: z.string().optional(),
      aws_region: z.string().optional(),
      start_date: z.string().optional(),
      end_date: z.string().optional(),
      candidate_pool: z.number().int().min(8).max(2000).default(24),
      rrf_k: z.number().int().min(1).max(1000).default(60),
      w_text: z.number().min(0).max(10).default(2),
      w_vector: z.number().min(0).max(10).default(1),
      w_trgm: z.number().min(0).max(10).default(1),
      fuzzy_threshold: z.number().min(0.1).max(1).default(0.3),
      ef_search: z.number().int().min(1).max(1000).default(40),
      iterative_scan: z.enum(["off", "strict_order", "relaxed_order"]).default("strict_order"),
      rerank: z.boolean().optional(),
      role: z.enum(["app_engineer", "auditor", "dba"]).default("app_engineer"),
    },
    async (args: Record<string, unknown>) => {
      const payload = pruneUndefined({
        query: args.query,
        incident_id: args.incident_id,
        cluster_id: args.cluster_id,
        kinds: args.kinds,
        limit: args.limit,
        source_systems: args.source_systems,
        account_name: args.account_name,
        severities: args.severities,
        environment: args.environment,
        service_name: args.service_name,
        engine_version: args.engine_version,
        aws_region: args.aws_region,
        start_date: args.start_date,
        end_date: args.end_date,
        candidate_pool: args.candidate_pool,
        rrf_k: args.rrf_k,
        w_text: args.w_text,
        w_vector: args.w_vector,
        w_trgm: args.w_trgm,
        fuzzy_threshold: args.fuzzy_threshold,
        ef_search: args.ef_search,
        iterative_scan: args.iterative_scan,
        rerank: args.rerank,
        role: args.role,
      });
      return wrap(await post("/v1/search", payload));
    }
  );

  server.tool(
    "follow_evidence_links",
    `Walk declared relationships out from evidence you already retrieved.

Relationships come from foreign keys, not text similarity, so this is how
you connect the measured backfill, pool behavior, and plan evidence.
Every hop re-checks the caller's ACL and stays inside the diagnostic
capture boundary when one is active.

Returns:
    Each reached record with the relation and depth that reached it.`,
    {
      seed_external_keys: z.array(z.string()).min(1).max(20),
      max_depth: z.number().int().min(0).max(8).default(2),
      role: z.enum(["app_engineer", "auditor", "dba"]).default("app_engineer"),
    },
    async (args: Record<string, unknown>) => {
      const payload = pruneUndefined({
        seed_external_keys: args.seed_external_keys,
        max_depth: args.max_depth,
        role: args.role,
      });
      return wrap(await post("/v1/tools/traverse", payload));
    }
  );

  server.tool(
    "compare_sources",
    `Compare specific records on revision, timing, scope, and relationships.

Use this to test an evidence-backed finding: it shows whether records share
a cluster and incident and whether an explicit relationship joins them.

Returns:
    Each record's scope and revision, plus the relationships between them.`,
    {
      external_keys: z.array(z.string()).min(1).max(20),
      role: z.enum(["app_engineer", "auditor", "dba"]).default("app_engineer"),
    },
    async (args: Record<string, unknown>) => {
      const payload = pruneUndefined({
        external_keys: args.external_keys,
        role: args.role,
      });
      return wrap(await post("/v1/tools/compare", payload));
    }
  );

  server.tool(
    "explain_ranking",
    `Show why Aurora ordered a retrieval the way it did.

Reads the persisted receipt for a run_id returned by search_evidence: each
candidate's per-arm positions, its RRF score, its match tier, and the stage
timings. Nothing is recomputed and no model is called.

Returns:
    Per-candidate arm positions and scores, plus stage timings.`,
    {
      run_id: z.string().uuid(),
      role: z.enum(["app_engineer", "auditor", "dba"]).default("app_engineer"),
    },
    async (args: Record<string, unknown>) => {
      const payload = pruneUndefined({
        run_id: args.run_id,
        role: args.role,
      });
      return wrap(await post("/v1/tools/explain-ranking", payload));
    }
  );

  server.tool(
    "synthesize_cited_answer",
    `Write the final diagnostic answer from persisted runs, with validated citations.

This is the last call. Pass every run_id that supports the three-part
question. The function reloads the exact visible evidence Aurora persisted,
refuses to synthesize if a required evidence kind is missing, and validates
every citation against the stored chunk quote and revision. The answer it
produces is delivered to the user directly, so you do not need to repeat it.

Returns:
    The validated answer, its numbered citations, and the synthesis mode.`,
    {
      question: z.string().min(1).max(4000),
      run_ids: z.array(z.string().uuid()).min(1).max(20),
      limit: z.number().int().min(1).max(8).default(8),
      role: z.enum(["app_engineer", "auditor", "dba"]).default("app_engineer"),
    },
    async (args: Record<string, unknown>) => {
      const payload = pruneUndefined({
        question: args.question,
        run_ids: args.run_ids,
        limit: args.limit,
        role: args.role,
      });
      return wrap(await post("/v1/tools/synthesize", payload));
    }
  );

  server.tool(
    "answer_with_citations",
    `Answer a diagnostic question end to end and return a cited finding.

Runs the whole deterministic loop server-side: decompose, retrieve once per
subquestion, escalate within a bounded budget, then synthesize a cited answer
from the persisted runs. The diagnostic path establishes the unbatched
backfill, pool exhaustion and recovery, and the plan regression that
ANALYZE did not resolve. Exposed to managed transports so a single call
reproduces the workbench answer against the same Aurora receipts.

Returns:
    The cited answer, its citations, and the agent run receipt.`,
    {
      question: z.string().min(1).max(4000),
      incident_id: z.string().optional(),
      cluster_id: z.string().optional(),
      kinds: z.array(z.enum(["incident", "change", "lock_evidence", "telemetry"])).optional(),
      limit: z.number().int().min(1).max(20).default(8),
      source_systems: z.array(z.string()).optional(),
      account_name: z.string().optional(),
      severities: z.array(z.string()).optional(),
      environment: z.string().optional(),
      service_name: z.string().optional(),
      engine_version: z.string().optional(),
      aws_region: z.string().optional(),
      start_date: z.string().optional(),
      end_date: z.string().optional(),
      candidate_pool: z.number().int().min(8).max(2000).default(24),
      rrf_k: z.number().int().min(1).max(1000).default(60),
      w_text: z.number().min(0).max(10).default(2),
      w_vector: z.number().min(0).max(10).default(1),
      w_trgm: z.number().min(0).max(10).default(1),
      fuzzy_threshold: z.number().min(0.1).max(1).default(0.3),
      ef_search: z.number().int().min(1).max(1000).default(40),
      iterative_scan: z.enum(["off", "strict_order", "relaxed_order"]).default("strict_order"),
      rerank: z.boolean().default(false),
      max_tool_calls: z.number().int().min(1).max(50).default(12),
      max_escalations: z.number().int().min(0).max(10).default(2),
      role: z.enum(["app_engineer", "auditor", "dba"]).default("app_engineer"),
    },
    async (args: Record<string, unknown>) => {
      const payload = pruneUndefined({
        question: args.question,
        incident_id: args.incident_id,
        cluster_id: args.cluster_id,
        kinds: args.kinds,
        limit: args.limit,
        source_systems: args.source_systems,
        account_name: args.account_name,
        severities: args.severities,
        environment: args.environment,
        service_name: args.service_name,
        engine_version: args.engine_version,
        aws_region: args.aws_region,
        start_date: args.start_date,
        end_date: args.end_date,
        candidate_pool: args.candidate_pool,
        rrf_k: args.rrf_k,
        w_text: args.w_text,
        w_vector: args.w_vector,
        w_trgm: args.w_trgm,
        fuzzy_threshold: args.fuzzy_threshold,
        ef_search: args.ef_search,
        iterative_scan: args.iterative_scan,
        rerank: args.rerank,
        max_tool_calls: args.max_tool_calls,
        max_escalations: args.max_escalations,
        role: args.role,
      });
      return wrap(await post("/v1/agent/answer", payload));
    }
  );
}
