"""Generate the stdio MCP server's tool registrations from the tool registry (T4).

Emits ``mcp-server/src/server.generated.ts``: one Zod input shape and one
``server.tool(...)`` registration per tool exposed via ``mcp``, each POSTing to the
tool's canonical ``/v1`` path. The hand-written ``mcp-server/src/server.ts`` imports
:func:`registerTools` from this file and owns only the transport wiring (fetch
helper, identity-free HTTP call, stdio connect).

The generated schema uses the registry's snake_case parameter names verbatim, so
one name identifies a parameter across the Strands, MCP, and Gateway transports.
This is the single source that makes G-17's cross-transport drift check meaningful.

Run ``python -m agent.generate_mcp_server`` to rewrite the committed file, or
``python -m agent.generate_mcp_server --check`` to diff against it (exit 1 on
drift). Gate G-17 uses :func:`render` directly.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

from agent.registry import ToolParam, ToolSpec, tools_for

GENERATED_PATH = Path("mcp-server/src/server.generated.ts")

_HEADER = """// Code generated by agent/generate_mcp_server.py from agent/registry.py.
// Do not edit by hand: run `python -m agent.generate_mcp_server` to regenerate.
// Gate G-17 fails CI if this file drifts from the registry.
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

type Post = (path: string, payload: Record<string, unknown>) => Promise<unknown>;
type Wrap = (result: unknown) => { content: { type: "text"; text: string }[] };

function pruneUndefined(payload: Record<string, unknown>): Record<string, unknown> {
  for (const key of Object.keys(payload)) {
    if (payload[key] === undefined) delete payload[key];
  }
  return payload;
}
"""


def _zod_scalar(param: ToolParam) -> str:
    """Render the Zod expression for one scalar (non-array) parameter."""
    if param.enum is not None:
        members = ", ".join(f'"{value}"' for value in param.enum)
        return f"z.enum([{members}])"
    if param.json_type == "string":
        expr = "z.string()"
        if param.str_format == "uuid":
            expr += ".uuid()"
        if param.min_length is not None:
            expr += f".min({param.min_length})"
        if param.max_length is not None:
            expr += f".max({param.max_length})"
        return expr
    if param.json_type in ("integer", "number"):
        expr = "z.number()"
        if param.json_type == "integer":
            expr += ".int()"
        if param.minimum is not None:
            expr += f".min({_num(param.minimum)})"
        if param.maximum is not None:
            expr += f".max({_num(param.maximum)})"
        return expr
    if param.json_type == "boolean":
        return "z.boolean()"
    if param.json_type == "object":
        return "z.record(z.unknown())"
    raise ValueError(f"unsupported scalar json_type {param.json_type!r} for {param.name}")


def _num(value: float) -> str:
    """Render a numeric literal without a trailing ``.0`` when it is integral."""
    return str(int(value)) if float(value).is_integer() else str(value)


def _zod_expr(param: ToolParam) -> str:
    """Render the full Zod expression for a parameter, including array/optional."""
    if param.json_type == "array":
        element = _zod_array_element(param)
        expr = f"z.array({element})"
        if param.min_length is not None:
            expr += f".min({param.min_length})"
        if param.max_length is not None:
            expr += f".max({param.max_length})"
    else:
        expr = _zod_scalar(param)
    if param.required:
        return expr
    if param.default is not None:
        return f"{expr}.default({_ts_literal(param.default)})"
    return f"{expr}.optional()"


def _zod_array_element(param: ToolParam) -> str:
    """Render the Zod expression for an array parameter's element type."""
    if param.enum is not None:
        members = ", ".join(f'"{value}"' for value in param.enum)
        return f"z.enum([{members}])"
    if param.item_type == "string":
        return "z.string().uuid()" if param.str_format == "uuid" else "z.string()"
    if param.item_type in ("integer", "number"):
        return "z.number().int()" if param.item_type == "integer" else "z.number()"
    if param.item_type == "boolean":
        return "z.boolean()"
    return "z.unknown()"


def _ts_literal(value: object) -> str:
    """Render a Python default as a TypeScript literal for a Zod ``.default()``."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return _num(value)
    if isinstance(value, str):
        return f'"{value}"'
    raise ValueError(f"unsupported default literal {value!r}")


def _tool_block(spec: ToolSpec) -> str:
    """Render one ``server.tool(...)`` registration for a tool."""
    params = tuple(p for p in spec.params if not p.identity_bound) + tuple(
        p for p in spec.params if p.identity_bound
    )
    shape_lines = [f"      {p.name}: {_zod_expr(p)}," for p in params]
    shape = "\n".join(shape_lines)
    payload_lines = [f"        {p.name}: args.{p.name}," for p in params]
    payload = "\n".join(payload_lines)
    description = _ts_template(spec.full_description())
    return f"""  server.tool(
    "{spec.name}",
    {description},
    {{
{shape}
    }},
    async (args: Record<string, unknown>) => {{
      const payload = pruneUndefined({{
{payload}
      }});
      return wrap(await post("{spec.http_path}", payload));
    }}
  );"""


def _ts_template(text: str) -> str:
    """Render a description as a TypeScript template literal, escaping backticks."""
    escaped = text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    return f"`{escaped}`"


def render() -> str:
    """Render the full ``server.generated.ts`` source from the registry.

    Returns:
        The complete TypeScript module text, newline-terminated.
    """
    blocks = [_tool_block(spec) for spec in tools_for("mcp")]
    body = "\n\n".join(blocks)
    return (
        _HEADER
        + "\nexport function registerTools(server: McpServer, post: Post, wrap: Wrap): void {\n"
        + body
        + "\n}\n"
    )


def main(argv: list[str] | None = None) -> int:
    """Write or check the generated MCP server file.

    Args:
        argv: CLI arguments; ``--check`` diffs instead of writing.

    Returns:
        Process exit code: 0 on success or match, 1 on drift under ``--check``.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="diff instead of write")
    args = parser.parse_args(argv)

    root = Path(__file__).resolve().parent.parent
    target = root / GENERATED_PATH
    rendered = render()

    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current == rendered:
            print(f"{GENERATED_PATH}: up to date")
            return 0
        print(f"{GENERATED_PATH}: DRIFT (regenerate with python -m agent.generate_mcp_server)")
        return 1

    target.write_text(rendered, encoding="utf-8")
    print(f"wrote {GENERATED_PATH} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
