"""Generate the AgentCore Gateway (Lambda-ARN) tool dispatch from the registry (T4).

Emits ``lambda_mcp/generated_dispatch.py``: a ``TOOLS`` dict mapping each tool name
to a callable that reads the Gateway's flat ``arguments`` dict, coerces each value
to the registry's declared type, and calls the owning ``backend.app.agent`` impl
with keyword arguments. The hand-written ``lambda_mcp/handler.py`` imports this
``TOOLS`` dict and owns only the Lambda envelope (tool-name resolution, the MCP
result shape, the invocation contract).

The Gateway target is a Lambda ARN: invocation travels the AWS control plane, so the
Lambda is a thin forwarder to the same impls the HTTP path uses, never a second
implementation. ``synthesize_cited_answer`` accepts the canonical ``run_ids`` list
and also coerces a legacy scalar ``run_id`` to a one-element list here, at the
adapter boundary, so existing callers do not break.

Run ``python -m agent.generate_gateway_dispatch`` to rewrite the committed file, or
``--check`` to diff (exit 1 on drift). Gate G-17 uses :func:`render` directly.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

from agent.registry import ToolParam, ToolSpec, tools_for

GENERATED_PATH = Path("lambda_mcp/generated_dispatch.py")

_HEADER = '''"""Code generated by agent/generate_gateway_dispatch.py from agent/registry.py.

Do not edit by hand: run ``python -m agent.generate_gateway_dispatch`` to
regenerate. Gate G-17 fails CI if this file drifts from the registry.
"""
from __future__ import annotations

from typing import Any, Callable

from backend.app.agent import (
    answer_with_citations_impl,
    compare_sources_impl,
    decompose_question_impl,
    explain_ranking_impl,
    follow_evidence_links_impl,
    search_evidence_impl,
    synthesize_cited_answer_from_runs_impl,
)


def _opt_int(value: Any, default: int) -> int:
    return default if value is None else int(value)


def _opt_float(value: Any, default: float) -> float:
    return default if value is None else float(value)


def _opt_bool(value: Any) -> bool | None:
    return None if value is None else bool(value)


def _run_ids(args: dict[str, Any]) -> list[str]:
    """Read run_ids, coercing a legacy scalar run_id to a one-element list."""
    run_ids = args.get("run_ids")
    if run_ids:
        return [str(value) for value in run_ids]
    single = args.get("run_id")
    return [str(single)] if single else []
'''


def _read_expr(param: ToolParam) -> str:
    """Render the Python expression that reads one param from the ``args`` dict."""
    key = f'args.get("{param.name}")'
    if param.json_type == "integer":
        return f'_opt_int({key}, {int(param.default) if param.default is not None else 0})'
    if param.json_type == "number":
        return f'_opt_float({key}, {float(param.default) if param.default is not None else 0.0})'
    if param.json_type == "boolean":
        if param.default is None:
            return f"_opt_bool({key})"
        return f'bool({key}) if {key} is not None else {bool(param.default)}'
    if param.json_type == "string":
        if param.required:
            return f'str({key} or "")'
        if param.default is not None:
            return f'str({key}) if {key} is not None else "{param.default}"'
        return key
    if param.json_type in ("array", "object"):
        if param.required:
            return f"{key} or []" if param.json_type == "array" else f"{key} or {{}}"
        return key
    raise ValueError(f"unsupported json_type {param.json_type!r} for {param.name}")


def _call_kwargs(spec: ToolSpec) -> list[str]:
    """Render the keyword arguments for a tool's impl call, in registry order."""
    kwargs: list[str] = []
    for param in spec.params:
        if spec.name == "synthesize_cited_answer" and param.name == "run_ids":
            kwargs.append("run_ids=_run_ids(args)")
            continue
        kwargs.append(f"{param.name}={_read_expr(param)}")
    return kwargs


def _dispatch_block(spec: ToolSpec) -> str:
    """Render one ``def _tool_<name>(args)`` dispatch function."""
    impl = _IMPL_NAMES[spec.name]
    kwargs = _call_kwargs(spec)
    if len(kwargs) == 1:
        call = f"{impl}({kwargs[0]})"
    else:
        joined = ",\n        ".join(kwargs)
        call = f"{impl}(\n        {joined},\n    )"
    return f"""def _tool_{spec.name}(args: dict[str, Any]) -> dict[str, Any]:
    return {call}"""


_IMPL_NAMES = {
    "decompose_question": "decompose_question_impl",
    "search_evidence": "search_evidence_impl",
    "follow_evidence_links": "follow_evidence_links_impl",
    "compare_sources": "compare_sources_impl",
    "explain_ranking": "explain_ranking_impl",
    "synthesize_cited_answer": "synthesize_cited_answer_from_runs_impl",
    "answer_with_citations": "answer_with_citations_impl",
}


def render() -> str:
    """Render the full ``generated_dispatch.py`` source from the registry.

    Returns:
        The complete Python module text, newline-terminated.
    """
    specs = tools_for("gateway")
    blocks = [_dispatch_block(spec) for spec in specs]
    entries = "\n".join(f'    "{spec.name}": _tool_{spec.name},' for spec in specs)
    table = (
        "\nTool = Callable[[dict[str, Any]], dict[str, Any]]\n"
        "TOOLS: dict[str, Tool] = {\n" + entries + "\n}\n"
    )
    return _HEADER + "\n\n" + "\n\n\n".join(blocks) + "\n\n" + table


def main(argv: list[str] | None = None) -> int:
    """Write or check the generated Gateway dispatch file.

    Args:
        argv: CLI arguments; ``--check`` diffs instead of writing.

    Returns:
        Process exit code: 0 on success or match, 1 on drift under ``--check``.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="diff instead of write")
    args = parser.parse_args(argv)

    root = Path(__file__).resolve().parent.parent
    target = root / GENERATED_PATH
    rendered = render()

    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current == rendered:
            print(f"{GENERATED_PATH}: up to date")
            return 0
        print(f"{GENERATED_PATH}: DRIFT (regenerate with python -m agent.generate_gateway_dispatch)")
        return 1

    target.write_text(rendered, encoding="utf-8")
    print(f"wrote {GENERATED_PATH} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
