-- sql/12_masking.sql - column masking for the auditor persona (design "scope B").
--
-- RLS (sql/11_roles_rls.sql) decides which ROWS a persona sees. This file decides
-- which COLUMNS the auditor sees inside a row it is allowed to see. Analyst never
-- reaches a restricted row, admin is the unmasked baseline, auditor is the point.
--
-- pgcolumnmask.policy_admin_rolname is NOT required. Measured on Aurora
-- PostgreSQL 18.3 with pg_columnmask 1.1.0: with that parameter unset (''), the
-- schema owner successfully created, used and dropped masking policies. The
-- parameter is sighup-context and settable only via the DB cluster parameter
-- group, so requiring it would make `make schema` fail on every workshop account
-- for no benefit.

CREATE EXTENSION IF NOT EXISTS pg_columnmask;

-- ---------------------------------------------------------------------------
-- 1. Masking functions.
--
-- IMMUTABLE and deterministic: the auditor's masked value must be byte-identical
-- in the app panel and in the pasted verify-SQL (Law 2, asserted by G-29).
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION casework.mask_redact(p_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT CASE WHEN p_value IS NULL THEN NULL ELSE '[REDACTED]' END
$$;

COMMENT ON FUNCTION casework.mask_redact(text) IS
  'Whole-value redaction for masking policies. A bare literal is rejected by '
  'pgcolumnmask ("Invalid masking function"), so the constant needs a function.';

-- Initial body: mask the WHOLE blob. refresh_mask_blob() narrows it to the
-- sensitive substrings. A build that skips the refresh therefore OVER-masks, which
-- fails closed; the reverse default would leak.
CREATE OR REPLACE FUNCTION retrieval.mask_blob(p_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT CASE WHEN p_value IS NULL THEN NULL ELSE '[REDACTED]' END
$$;

COMMENT ON FUNCTION retrieval.mask_blob(text) IS
  'Substring redaction inside the rendered chunk_text. Body is GENERATED by '
  'retrieval.refresh_mask_blob() from the restricted rows sensitive values (A5): '
  'never hand-write the pattern set. Ships masking the whole blob so a skipped '
  'refresh over-masks rather than leaks.';

-- ---------------------------------------------------------------------------
-- 2. Pattern generation (A5): the pattern set is measured from the corpus.
--
-- Regex metacharacters in the literals are escaped before they become patterns.
-- This is not hypothetical: the canonical restricted account is
-- 'Northstar Foods (fictional)', and unescaped parentheses would compile as a
-- capture group that matches 'Northstar Foods fictional' and misses the real value.
--
-- The generated matcher is case-INSENSITIVE ('gi'). G-29's corpus-wide leak scan
-- is ILIKE, so a case-sensitive mask would redact the canonical row, pass the
-- "masking is real" assertion, and then fail the leak scan on any case variant
-- elsewhere in the corpus. Measured: 'NORTHSTAR FOODS (FICTIONAL)' survives a 'g'
-- mask and is caught by 'gi'.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION retrieval.sensitive_literals()
RETURNS TABLE (literal text)
LANGUAGE sql
STABLE
AS $$
  SELECT DISTINCT v.literal
    FROM casework.support_cases sc
    JOIN casework.evidence_items e ON e.evidence_id = sc.evidence_id
    CROSS JOIN LATERAL (
      VALUES (sc.account_name), (sc.customer_commitment), (sc.description)
    ) AS v(literal)
   WHERE coalesce(e.acl ->> 'visibility', 'restricted') = 'restricted'
     AND v.literal IS NOT NULL
     AND length(v.literal) > 0
   ORDER BY 1
$$;

COMMENT ON FUNCTION retrieval.sensitive_literals() IS
  'The source of the mask pattern set (A5): measured from the restricted rows, '
  'never hand-written. Deliberately BROADER than G-29 gates own needle set, which '
  'adds NOT is_deleted and a 6-character floor: masking a soft-deleted restricted '
  'literal over-masks, while missing one would leak. The gate does not call this '
  'function -- it re-derives the set from the same tables.';

CREATE OR REPLACE FUNCTION retrieval.refresh_mask_blob()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_expression text := 'p_value';
  v_literal    text;
  v_count      integer := 0;
BEGIN
  FOR v_literal IN SELECT literal FROM retrieval.sensitive_literals()
  LOOP
    v_expression := format(
      'regexp_replace(%s, %L, %L, %L)',
      v_expression,
      regexp_replace(v_literal, '([.^$*+?()\[\]{}|\\-])', '\\\1', 'g'),
      '[REDACTED]',
      'gi'
    );
    v_count := v_count + 1;
  END LOOP;

  IF v_count = 0 THEN
    RAISE EXCEPTION
      'no restricted sensitive literals found; retrieval.mask_blob would become a '
      'no-op and the auditor would read customer identity in chunk_text. Seed the '
      'restricted rows before refreshing the mask.';
  END IF;

  EXECUTE format(
    $fn$
      CREATE OR REPLACE FUNCTION retrieval.mask_blob(p_value text)
      RETURNS text
      LANGUAGE sql
      IMMUTABLE
      PARALLEL SAFE
      AS $body$
        SELECT CASE WHEN p_value IS NULL THEN NULL ELSE %s END
      $body$
    $fn$,
    v_expression
  );

  RETURN v_count;
END
$$;

-- CREATE OR REPLACE preserves the function's ACL (measured, including via
-- plpgsql EXECUTE format), so the personas' EXECUTE grant from section 4
-- survives every regeneration. If it did not, the auditor would start failing
-- with 42501 after the first search-index build.
COMMENT ON FUNCTION retrieval.refresh_mask_blob() IS
  'Regenerates retrieval.mask_blob from retrieval.sensitive_literals(). Run after '
  'every seed or admission that adds a restricted row. Raises if the corpus holds '
  'no restricted literals rather than generating a no-op mask.';

-- Bootstrap refresh, GUARDED. It must be guarded because `make schema` runs before
-- `make seed-casework`: on a freshly provisioned account the corpus is empty, so an
-- unconditional call would hit the "no restricted sensitive literals" raise above
-- and fail the schema build for every workshop account. Skipping is safe in exactly
-- one direction: the shipped mask_blob body redacts the WHOLE blob, so a database
-- whose refresh has not run yet over-masks. The search-index build calls the refresh
-- inside the build transaction (backend/app/search_index.py), which is the point at
-- which a corpus exists.
DO $$
DECLARE
  v_count integer;
BEGIN
  SELECT count(*) INTO v_count FROM retrieval.sensitive_literals();
  IF v_count = 0 THEN
    RAISE NOTICE
      'no restricted literals in the corpus yet (pre-seed); retrieval.mask_blob '
      'stays at its whole-blob default and the search-index build will refresh it';
  ELSE
    PERFORM retrieval.refresh_mask_blob();
    RAISE NOTICE 'retrieval.mask_blob regenerated from % literals', v_count;
  END IF;
END
$$;

-- ---------------------------------------------------------------------------
-- 3. Masking policies, bound to persona_auditor only.
--
-- Re-runnable: `make schema` runs this file on every build, and
-- create_masking_policy raises 42710 on a duplicate (name, table, weight) and
-- 42704 on the same (name, table) at a different weight. Dropping first is the
-- only way to let a changed expression set replace the old one.
--
-- drop_masking_policy takes (policy_name, table_name regclass) -- measured, two
-- arguments -- so the loop carries pairs, not names. Dropping a policy that is
-- not there raises 42704 (undefined_object), which is the expected first-run
-- condition and the only one swallowed here: a 42P01 from a missing TABLE is a
-- real error and must propagate.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  v_target record;
BEGIN
  FOR v_target IN
    SELECT *
      FROM (VALUES
        ('mask_support_cases', 'casework.support_cases'),
        ('mask_documents',     'retrieval.documents'),
        ('mask_chunks',        'retrieval.chunks')
      ) AS t(policy_name, table_name)
  LOOP
    BEGIN
      EXECUTE format(
        'CALL pgcolumnmask.drop_masking_policy(%L, %L::regclass)',
        v_target.policy_name, v_target.table_name
      );
      RAISE NOTICE 'dropped existing masking policy % on %',
        v_target.policy_name, v_target.table_name;
    EXCEPTION
      WHEN undefined_object THEN
        NULL;  -- first run on this database: nothing to drop
    END;
  END LOOP;
END
$$;

-- Legal 5-argument form: args 4-6 of create_masking_policy have defaults.
-- Measured on Aurora PostgreSQL 18.3, pg_columnmask 1.1.0: prokind = 'p'
-- (procedures), hence CALL rather than SELECT.
CALL pgcolumnmask.create_masking_policy(
  'mask_support_cases',
  'casework.support_cases',
  jsonb_build_object(
    'account_name',        'pgcolumnmask.mask_text(account_name)',
    'description',         'casework.mask_redact(description)',
    'customer_commitment', 'casework.mask_redact(customer_commitment)'
  ),
  ARRAY['persona_auditor']::name[],
  100
);

CALL pgcolumnmask.create_masking_policy(
  'mask_documents',
  'retrieval.documents',
  jsonb_build_object('account_name', 'pgcolumnmask.mask_text(account_name)'),
  ARRAY['persona_auditor']::name[],
  100
);

CALL pgcolumnmask.create_masking_policy(
  'mask_chunks',
  'retrieval.chunks',
  jsonb_build_object(
    'account_name', 'pgcolumnmask.mask_text(account_name)',
    'chunk_text',   'retrieval.mask_blob(chunk_text)'
  ),
  ARRAY['persona_auditor']::name[],
  100
);

-- ---------------------------------------------------------------------------
-- 4. EXECUTE on the mask functions.
--
-- NOT optional, and not covered by sql/11. Measured on Aurora PostgreSQL 18.3:
-- pg_columnmask evaluates a masking expression with the QUERYING role's
-- privileges, so a persona without EXECUTE on the mask function gets
--   ERROR: 42501 permission denied for function mask_redact
-- on an ordinary SELECT -- the auditor cannot read the table at all.
--
-- sql/11 cannot cover these: its GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA
-- retrieval runs BEFORE this file creates retrieval.mask_blob, it never lists
-- schema casework, and its ALTER DEFAULT PRIVILEGES covers TABLES only. A default
-- PUBLIC grant would mask the gap today; naming the grantees keeps it correct if
-- PUBLIC is ever revoked, as sql/11:331 already does for admit_evidence.
--
-- Granted to all three personas, not just the auditor: the mask expression is
-- only ever invoked for a role the policy names, so a grant to analyst and admin
-- costs nothing and stops a future policy widening from failing with 42501.
-- ---------------------------------------------------------------------------

GRANT EXECUTE ON FUNCTION casework.mask_redact(text)
  TO persona_analyst, persona_admin, persona_auditor;
GRANT EXECUTE ON FUNCTION retrieval.mask_blob(text)
  TO persona_analyst, persona_admin, persona_auditor;
GRANT EXECUTE ON FUNCTION retrieval.sensitive_literals()
  TO persona_analyst, persona_admin, persona_auditor;
