-- sql/12_masking.sql - column masking for personas without clearance (design "scope B").
--
-- RLS (sql/11_roles_rls.sql) decides which ROWS a persona sees. This file decides
-- which COLUMNS a persona sees inside a row it is allowed to see. The two are not
-- interchangeable, and this capture is the cleanest possible demonstration of why:
--
--   casework.pg_stat_activity_samples holds 270 rows under a workshop-visible lock
--   observation. Measured on this capture, 180 of them repeat the query text of a
--   restricted Performance Insights row VERBATIM in their query column, and 60 more
--   repeat a second one. RLS cannot fix that. Hiding those rows would hide the
--   nine-row pg_stat_activity topology, the six blocked writers, and the blocking
--   PID -- which is the entire subject of the lab. The row must stay readable and
--   the column must not.
--
-- So: RLS scopes the derived evidence (sql/11 section 4-6), masking redacts the
-- statement text that survives inside rows every persona is meant to read.
--
-- pgcolumnmask.policy_admin_rolname is NOT required. Measured on Aurora
-- PostgreSQL 18.3 with pg_columnmask 1.1.0: with that parameter unset, the schema
-- owner successfully created, used and dropped masking policies. The parameter is
-- sighup-context and settable only via the DB cluster parameter group, so
-- requiring it would make this file fail on every workshop account for no benefit.

CREATE EXTENSION IF NOT EXISTS pg_columnmask;

-- ---------------------------------------------------------------------------
-- 1. Masking functions.
--
-- IMMUTABLE and deterministic: the masked value must be byte-identical in the app
-- panel and in the pasted verify-SQL (Law 2, asserted by G-29).
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION casework.mask_redact(p_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT CASE WHEN p_value IS NULL THEN NULL ELSE '[REDACTED]' END
$$;

COMMENT ON FUNCTION casework.mask_redact(text) IS
  'Whole-value redaction for masking policies on text columns. A bare literal is '
  'rejected by pgcolumnmask ("Invalid masking function"), so the constant needs a '
  'function. Do NOT use on a jsonb column: see casework.mask_redact_json.';

-- The jsonb counterpart, and it is not interchangeable with the text one.
-- pg_columnmask casts a masking expression back to the masked column's type, so a
-- jsonb column masked with casework.mask_redact() yields the bare string
-- "[REDACTED]" and then fails the cast:
--   ERROR: invalid input syntax for type json
--   DETAIL: Token "REDACTED" is invalid.
-- Measured: that made casework.pg_stat_statements_samples completely unreadable for
-- persona_app_engineer -- not redacted, ERROR. A masking policy that renders a
-- table unreadable is a broken app, not enforcement, and it would have shipped
-- looking like a permissions bug. The value returned here is valid jsonb.
CREATE OR REPLACE FUNCTION casework.mask_redact_json(p_value jsonb)
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT CASE WHEN p_value IS NULL THEN NULL ELSE '"[REDACTED]"'::jsonb END
$$;

COMMENT ON FUNCTION casework.mask_redact_json(jsonb) IS
  'Whole-value redaction for masking policies on jsonb columns. Returns the jsonb '
  'string "[REDACTED]" so pgcolumnmask cast back to jsonb succeeds.';

-- Initial body: mask the WHOLE blob. refresh_mask_blob() narrows it to the
-- sensitive substrings. A build that skips the refresh therefore OVER-masks, which
-- fails closed; the reverse default would leak.
CREATE OR REPLACE FUNCTION retrieval.mask_blob(p_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT CASE WHEN p_value IS NULL THEN NULL ELSE '[REDACTED]' END
$$;

COMMENT ON FUNCTION retrieval.mask_blob(text) IS
  'Substring redaction inside rendered text. Body is GENERATED by '
  'retrieval.refresh_mask_blob() from the restricted rows captured statements '
  '(A5): never hand-write the pattern set. Ships masking the whole blob so a '
  'skipped refresh over-masks rather than leaks.';

-- ---------------------------------------------------------------------------
-- 2. Pattern generation (A5): the pattern set is measured from the capture.
--
-- The sensitive literal in a live capture is the resolved SQL statement text that
-- Performance Insights returned. That is the same thing
-- labs/incident/run_live_workshop.py classifies on: a captured observation
-- carrying resolved statement text becomes restricted, one carrying PI's
-- "Unknown" placeholder stays workshop. This function re-derives the literal set
-- from whatever the run actually measured, so it holds for any participant's run
-- rather than for one recorded corpus.
--
-- Regex metacharacters are escaped before the literals become patterns. This is
-- not hypothetical here, it is unavoidable: every literal is SQL, so every literal
-- contains parentheses, dollar-sign placeholders ($1, $2), asterisks and dots.
-- Unescaped, 'count(*)::bigint' compiles as a capture group with a quantifier and
-- either fails to match or throws.
--
-- The generated matcher is case-INSENSITIVE ('gi'), because G-29's leak scan is
-- ILIKE. Measured on the authored corpus this replaced: a 'g' mask let an
-- upper-cased variant through the mask and into the leak scan.
--
-- A length floor of 24 characters keeps the pattern set to statements rather than
-- fragments. Without it a short captured statement could reduce to a pattern like
-- 'SELECT 1' and redact half the corpus, which reads as a broken app rather than
-- as enforcement.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION retrieval.sensitive_literals()
RETURNS TABLE (literal text)
LANGUAGE sql
STABLE
AS $$
  SELECT DISTINCT btrim(t.structured ->> 'statement') AS literal
    FROM casework.telemetry_evidence t
    JOIN casework.evidence_items e ON e.evidence_id = t.evidence_id
   WHERE coalesce(e.acl ->> 'visibility', 'restricted') = 'restricted'
     AND t.structured ->> 'statement' IS NOT NULL
     AND length(btrim(t.structured ->> 'statement')) >= 24
   ORDER BY 1
$$;

COMMENT ON FUNCTION retrieval.sensitive_literals() IS
  'The source of the mask pattern set (A5): measured from the restricted captured '
  'observations, never hand-written. Returns the resolved Performance Insights '
  'statement text of every restricted evidence row in the current capture.';

CREATE OR REPLACE FUNCTION retrieval.refresh_mask_blob()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_expression text := 'p_value';
  v_literal    text;
  v_count      integer := 0;
BEGIN
  FOR v_literal IN SELECT literal FROM retrieval.sensitive_literals()
  LOOP
    -- Collapse each run of whitespace in the literal into a matcher that accepts
    -- BOTH real whitespace and the two-character escape sequences that appear when
    -- the same text is serialized inside a jsonb column. Two measured reasons:
    --
    -- (1) The captured statement is indented as the lab wrote it, and the SAME
    --     statement is re-rendered with collapsed whitespace elsewhere ("... DB
    --     load 4.5000: UPDATE workbench_lab.orders SET status = $1 ..."). A
    --     literal-whitespace pattern matched the raw column and missed the
    --     re-rendered copy.
    --
    -- (2) casework.pg_stat_activity_samples.raw_row is jsonb. Casting it to text
    --     turns every newline into the two characters backslash-n, which \s cannot
    --     match. Measured leak: with a plain \s+ pattern, mask_blob redacted the
    --     query column and returned raw_row verbatim, so persona_app_engineer read
    --     the restricted statement out of the jsonb copy one column over. The
    --     matcher below accepts (\s|\\[a-z])+ so both forms are caught.
    v_expression := format(
      'regexp_replace(%s, %L, %L, %L)',
      v_expression,
      regexp_replace(
        regexp_replace(v_literal, '([.^$*+?()\[\]{}|\\-])', '\\\1', 'g'),
        '(\\?\s)+', '(\\s|\\\\[a-z])+', 'g'
      ),
      '[REDACTED]',
      'gi'
    );
    v_count := v_count + 1;
  END LOOP;

  IF v_count = 0 THEN
    RAISE EXCEPTION
      'no restricted captured statements found; retrieval.mask_blob would become a '
      'no-op and a persona without clearance would read the captured SQL in full. '
      'Run the live capture before refreshing the mask.';
  END IF;

  EXECUTE format(
    $fn$
      CREATE OR REPLACE FUNCTION retrieval.mask_blob(p_value text)
      RETURNS text
      LANGUAGE sql
      IMMUTABLE
      PARALLEL SAFE
      AS $body$
        SELECT CASE WHEN p_value IS NULL THEN NULL ELSE %s END
      $body$
    $fn$,
    v_expression
  );

  RETURN v_count;
END
$$;

-- CREATE OR REPLACE preserves the function's ACL (measured, including via plpgsql
-- EXECUTE format), so the personas' EXECUTE grant from section 4 survives every
-- regeneration. If it did not, personas would start failing with 42501 after the
-- first search-index build.
COMMENT ON FUNCTION retrieval.refresh_mask_blob() IS
  'Regenerates retrieval.mask_blob from retrieval.sensitive_literals(). Run after '
  'every capture admission that adds a restricted row. Raises if the capture holds '
  'no restricted statements rather than generating a no-op mask.';

-- Bootstrap refresh, GUARDED. It must be guarded because this file runs before
-- `make live-workshop`: on a freshly provisioned account no capture exists, so an
-- unconditional call would hit the raise above and fail the schema build for every
-- workshop account. Skipping is safe in exactly one direction: the shipped
-- mask_blob body redacts the WHOLE blob, so a database whose refresh has not run
-- yet over-masks. The search-index build calls the refresh inside the build
-- transaction, which is the point at which a capture exists.
DO $$
DECLARE
  v_count integer;
BEGIN
  SELECT count(*) INTO v_count FROM retrieval.sensitive_literals();
  IF v_count = 0 THEN
    RAISE NOTICE
      'no restricted captured statements yet (pre-capture); retrieval.mask_blob '
      'stays at its whole-blob default and the search-index build will refresh it';
  ELSE
    PERFORM retrieval.refresh_mask_blob();
    RAISE NOTICE 'retrieval.mask_blob regenerated from % captured statement(s)',
      v_count;
  END IF;
END
$$;

-- ---------------------------------------------------------------------------
-- 3. Masking policies.
--
-- Bound to persona_app_engineer AND persona_auditor, not to the auditor alone.
-- The authored corpus this replaced masked only the auditor, because RLS already
-- denied the analyst every restricted ROW and there was nothing left to redact.
-- That is no longer true: the leak measured above is restricted statement text
-- inside workshop-visible raw sample rows, which App Engineer reads in full. A
-- policy naming only the auditor would leave the wider hole open.
--
-- persona_dba is the unmasked baseline and is deliberately absent. Its clearance
-- comes from can_see_restricted (sql/11 section 1), so the same statement is
-- readable to the DBA and redacted for the other two -- which is the comparison
-- the lab asks a participant to run.
--
-- Re-runnable: create_masking_policy raises 42710 on a duplicate
-- (name, table, weight) and 42704 on the same (name, table) at a different weight.
-- Dropping first is the only way to let a changed expression set replace the old.
--
-- drop_masking_policy takes (policy_name, table_name regclass) -- measured, two
-- arguments -- so the loop carries pairs, not names. Dropping a policy that is not
-- there raises 42704 (undefined_object), which is the expected first-run condition
-- and the only one swallowed here: 42P01 from a missing TABLE is a real error and
-- must propagate.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  v_target record;
BEGIN
  FOR v_target IN
    SELECT *
      FROM (VALUES
        ('mask_activity_query',     'casework.pg_stat_activity_samples'),
        ('mask_statement_phase',    'casework.pg_stat_statements_samples'),
        ('mask_telemetry',          'casework.telemetry_evidence'),
        -- Dropped unconditionally: an earlier revision of this file created a
        -- chunk_text policy that broke every search function (see section 3), so a
        -- database built with that revision must have it removed on re-run rather
        -- than silently keeping a policy this file no longer creates.
        ('mask_chunks',             'retrieval.chunks')
      ) AS t(policy_name, table_name)
  LOOP
    BEGIN
      EXECUTE format(
        'CALL pgcolumnmask.drop_masking_policy(%L, %L::regclass)',
        v_target.policy_name, v_target.table_name
      );
      RAISE NOTICE 'dropped existing masking policy % on %',
        v_target.policy_name, v_target.table_name;
    EXCEPTION
      WHEN undefined_object THEN
        NULL;  -- first run on this database: nothing to drop
    END;
  END LOOP;
END
$$;

-- Legal 5-argument form: args 4-6 of create_masking_policy have defaults.
-- Measured on Aurora PostgreSQL 18.3, pg_columnmask 1.1.0: prokind = 'p'
-- (procedures), hence CALL rather than SELECT.

-- The measured leak. RLS keeps these 270 rows readable on purpose (the lock
-- topology is the lesson); the query column is where the restricted statement
-- text reappears, so it is redacted by substring rather than wholesale. The
-- surrounding pid, wait_event, and state columns stay intact and are what the lab
-- actually reads.
CALL pgcolumnmask.create_masking_policy(
  'mask_activity_query',
  'casework.pg_stat_activity_samples',
  jsonb_build_object(
    'query',   'retrieval.mask_blob(query)',
    'raw_row', 'retrieval.mask_blob(raw_row::text)'
  ),
  ARRAY['persona_app_engineer', 'persona_auditor']::name[],
  100
);

-- Gated on the capture run in sql/11, so every persona reads these three rows.
-- The queries array holds statement text verbatim.
--
-- WHOLE-VALUE redaction here, not the substring mask, and this is the one place
-- the difference is forced rather than chosen. pg_stat_statements stores
-- NORMALIZED query text; Performance Insights returned the statement as executed.
-- Measured on this capture, the same UPDATE appears in pg_stat_statements as
--   "UPDATE workbench_lab.orders SET status = $1, updated_at = clock_timestamp()
--    WHERE order_id = $2"
-- and in PI with a RETURNING clause and different indentation. No pattern derived
-- from retrieval.sensitive_literals() can match a string the source system rewrote
-- before storing it -- measured: mask_blob redacted raw_row and returned the
-- queries array in full. A substring mask that cannot see its target is worse than
-- no mask, because it reports success. The columns are redacted wholesale instead:
-- the phase counters (calls, rows, total_exec_time, delta_from_before) are what
-- the lab reads and they stay intact.
CALL pgcolumnmask.create_masking_policy(
  'mask_statement_phase',
  'casework.pg_stat_statements_samples',
  jsonb_build_object(
    'queries', 'casework.mask_redact_json(queries)',
    'raw_row', 'casework.mask_redact_json(raw_row)'
  ),
  ARRAY['persona_app_engineer', 'persona_auditor']::name[],
  100
);

-- casework.telemetry_evidence is deliberately NOT masked, and this is a REVERSAL:
-- an earlier revision of this file created a mask_telemetry policy over
-- (body, structured) bound to persona_auditor. It is dropped above and must not
-- come back. Two measurements killed it, both on Aurora PostgreSQL 18.3,
-- pg_columnmask 1.1.0, probe database dat410_rls_probe_test, 2026-08-03.
--
-- 1. IT CRASHED THE INSTANCE. casework.v_evidence_documents (sql/01_schema.sql)
--    joins this table to reach the telemetry branch of the searchable evidence.
--    With the policy in force:
--      BEGIN; SET LOCAL ROLE persona_auditor;
--      SELECT count(*) FROM casework.v_evidence_documents;
--    terminated the backend -- SSL EOF, connection lost -- and restarted the whole
--    shared Aurora instance (pg_postmaster_start_time moved). Not an error, a
--    crash. pg_columnmask's own HINT says to exclude masked columns from
--    "predicates or joins", but this join is on evidence_id, an UNMASKED key, so
--    this is undocumented behavior rather than the stated restriction. AWS's
--    dynamic-masking documentation states masking applies to join conditions and
--    subqueries; it does not document this crash.
--    The blast radius was the shipped app, not just tests:
--    GET /v1/evidence/{id}?role=auditor (backend/app/main.py), three reads in
--    backend/app/search_index.py, and sql/04_diagnostics.sql.
--    Measured after the drop: the same query returns 110 rows, the app's
--    evidence_detail shape returns 110, and pg_postmaster_start_time is unchanged.
--
-- 2. IT PROTECTED NOTHING ANYWAY, so there is no security cost to dropping it and
--    no reason to rewrite the view around it. retrieval.chunks.chunk_text is the
--    indexed copy of this table's body and is deliberately unmasked (see
--    below). Measured: for all 5 of 5 restricted telemetry rows, the statement text
--    the policy redacted appears VERBATIM in a current chunk with
--    acl_visibility = 'restricted' -- which persona_auditor reads raw, because the
--    auditor holds can_see_restricted. The policy redacted one copy of a string and
--    left the other in the retrieval path the workshop is about.
--
-- The correct tool here is the one already applied: RLS. Measured row scoping on
-- this table -- persona_app_engineer 101, persona_dba 106, owner 106, and
-- app_engineer reaches 0 rows whose body carries restricted statement text. The
-- persona that must not read the captured statement never reaches the row.
-- persona_auditor reading it raw is the clearance sql/11 section 1 grants on
-- purpose, identical to persona_dba, which this policy never named either.

-- retrieval.chunks.chunk_text is deliberately NOT masked. This is the one place
-- where masking and retrieval are incompatible, it was measured rather than
-- reasoned about, and the reason is worth stating because the omission looks like
-- an oversight:
--
--   pg_columnmask refuses predicates on a masked column --
--     ERROR: Predicates on masked columns are not allowed
--   and retrieval.full_text_search, vector_search and fuzzy_search all return
--   left(regexp_replace(c.chunk_text, '\s+', ' ', 'g'), 700) AS snippet
--   out of a LATERAL subquery (sql/03_search_functions.sql:398, 513, 649, 990).
--   With a chunk_text mask in force every one of those functions fails outright:
--     ERROR: failed to postpone qual containing lateral reference
--
-- Measured on this capture: with a chunk_text policy bound to persona_auditor, the
-- auditor's full_text_search raised that error while App Engineer and DBA returned
-- 20 rows. Re-bound to persona_app_engineer, App Engineer broke identically -- so
-- this is a property of masking that column, not of one persona. Masking
-- chunk_text does not degrade retrieval, it removes it.
--
-- Not masking it is correct rather than merely convenient, because RLS already
-- covers this exact column. Measured: restricted current chunks reachable are 0
-- for persona_app_engineer, 5 for persona_auditor and 5 for persona_dba. The
-- persona that must not read the captured statement never reaches the row, so
-- there is nothing left for a column mask to protect. The auditor and the DBA both
-- hold can_see_restricted (sql/11 section 1) and are cleared for it by design --
-- redacting the auditor's snippet would contradict the clearance the same file
-- grants.
--
-- The asymmetry with casework.pg_stat_activity_samples above is the whole point of
-- shipping both files: that table's rows are workshop-visible to everyone and its
-- query column leaks, so it needs masking. This table's rows are already scoped,
-- so it needs RLS. Applying the wrong tool to either one breaks something.
--
-- WHAT THIS DOES NOT HIDE, stated plainly so nobody claims more than it does.
-- Measured after both files are applied, persona_app_engineer can still read SQL
-- text in exactly two current workshop chunks:
--
--   LOCK-<suffix>-01  "Blocked statement: UPDATE workbench_lab.orders SET ...
--                      Blocking statement: CREATE INDEX idx_orders_customer_created ..."
--   TEL-<suffix>-R01  "Executed SQL: CREATE INDEX CONCURRENTLY idx_orders_customer_created ..."
--
-- That is correct and must not be "fixed". Those two rows ARE the lab: the first is
-- the measured Lock:relation proof that sql/10_admission.sql refuses a capture
-- without, and the second is the remediation that resolves it. Restricting them
-- would hide the incident from the persona whose job is to investigate it, and the
-- statements in question are the participant's own DML against their own
-- workbench_lab schema -- not a third party's query text.
--
-- So the enforced claim is narrow and true: what a persona without clearance
-- cannot read is the resolved statement text Performance Insights returned, in
-- every place it lands -- the derived evidence (RLS), the PI sample it came from (RLS),
-- and the raw pg_stat_activity copy that repeats it (masking). The claim is NOT
-- "no SQL is visible". Anyone writing guide copy off this file should say the
-- former.

-- ---------------------------------------------------------------------------
-- 4. EXECUTE on the mask functions.
--
-- NOT optional, and not covered by sql/11. Measured on Aurora PostgreSQL 18.3:
-- pg_columnmask evaluates a masking expression with the QUERYING role's
-- privileges, so a persona without EXECUTE on the mask function gets
--   ERROR: 42501 permission denied for function mask_redact
-- on an ordinary SELECT -- the persona cannot read the table at all.
--
-- sql/11 cannot cover these: its GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA
-- retrieval runs BEFORE this file creates retrieval.mask_blob, it never lists
-- schema casework, and its ALTER DEFAULT PRIVILEGES covers TABLES only. A default
-- PUBLIC grant would mask the gap today; naming the grantees keeps it correct if
-- PUBLIC is ever revoked, as sql/11 already does for admit_evidence.
--
-- Granted to all three personas, not just the masked ones: the mask expression is
-- only ever invoked for a role its policy names, so a grant to the DBA costs
-- nothing and stops a future policy widening from failing with 42501.
-- ---------------------------------------------------------------------------

GRANT EXECUTE ON FUNCTION casework.mask_redact(text)
  TO persona_app_engineer, persona_dba, persona_auditor;
GRANT EXECUTE ON FUNCTION casework.mask_redact_json(jsonb)
  TO persona_app_engineer, persona_dba, persona_auditor;
GRANT EXECUTE ON FUNCTION retrieval.mask_blob(text)
  TO persona_app_engineer, persona_dba, persona_auditor;
GRANT EXECUTE ON FUNCTION retrieval.sensitive_literals()
  TO persona_app_engineer, persona_dba, persona_auditor;
